#!/bin/bash

#Color Variables

NC='\e[0m'
BLACK='\e[0;30m'
RED='\e[0;31m'
GREEN='\e[0;32m'
WHITE='\e[1;37m'
ORANGE='\e[0;33m'
BLUE='\e[0;34m'
PURPLE='\e[0;35m'
CYAN='\e[0;36m'
YELLOW='\e[1;33m'
DARGRAY='\e[1;30m'

#Lighter Colors
LIGRAY='\e[0;37m'
LIGREEN='\e[1;32m'
LIRED='\e[1;31m'
LIBLUE='\e[1;34m'
LIPURPLE='\e[1;35m'
LICYAN='\e[1;36m'

#Background Color Variables

BACKBLACK='\e[0;40m'
BACKRED='\e[0;41m'
BACKGREEN='\e[0;42m'
BACKWHITE='\e[1;47m'
BACKORANGE='\e[0;43m'
BACKBLUE='\e[0;44m'
BACKPURPLE='\e[0;45m'
BACKCYAN='\e[0;46m'
BACKYELLOW='\e[1;43m'

#Lighter Colors
BACKLIGRAY='\e[0;47m'
BACKLIGREEN='\e[1;42m'
BACKLIRED='\e[1;41m'
BACKLIBLUE='\e[1;44m'
BACKLIPURPLE='\e[1;45m'
BACKLICYAN='\e[1;46m'

#Markup Variables
UNDERLINE='\e[4m'
DOUBLEUNDERLINE='\e[21m'
BOLD='\e[1m'
BLINK='\e[5m'
REVVID='\e[7m'

if [ "$(whoami)" == "root" ]; then
    sudo="sudo"
else
    sudo=""
fi

if ! wget --spider https://github.com &>/dev/null; then
    printf "${RED}${BOLD}Error: ${BLUE}https://github.com${RED} did not respond! Try checking your internet connection.${NC}\n\n"
    exit 1
fi

$sudo apt update || printf "\n\n${RED}${BOLD}Error: ${RED}Failed to update apt repositories!${NC}\n"; exit 1

if [ "$*" == "-y"]; then
    $sudo apt upgrade -y || printf "\n\n${RED}Failed to upgrade packages!${NC}\n"; exit 1
else
    $sudo apt upgrade || printf "\n\n${RED}Failed to upgrade packages!${NC}\n"; exit 1
fi
if [ "$*" == "--autoremove" || "$*" == "-a" ]; then
    $sudo apt autoremove -y &>/dev/null || printf "\n\n${RED}Failed to autoremove unneeded packages!${NC}\n"; exit 1
fi
